# Week 1 — Python and NumPy Foundations for AI

This three-hour practical session introduces the array-based thinking used throughout the AI toolkit: NumPy, Pandas, scikit-learn, PyTorch, and image or signal processing libraries.

## Learning outcomes

By the end of the session, you should be able to:

- confirm that your Python environment can run the course notebooks;
- create and inspect NumPy arrays using `shape`, `ndim`, `dtype`, and `size`;
- predict the shapes produced by indexing, reshaping, and broadcasting;
- replace simple Python loops with vectorized NumPy operations;
- aggregate data along the correct axis;
- apply array operations to a small AI-related preprocessing task.

## Roadmap

0. Introduction — Why NumPy
1. Arrays & Memory Model  
   1.1 Python Lists vs NumPy Arrays  
   1.2 NumPy Array Attributes
   1.3 Creating NumPy Arrays
2. Mastering Slicing & Indexing (Core for `.iloc` later)  
   2.1 1D indexing and slicing  
   2.2 2D slicing — rows, columns, blocks  
3. Reshaping, Stacking, Concatenation
4. Broadcasting
5. Vectorization
6. Axis Operations & Aggregations  
7. Transposing
8. Challenging Exercises
9. Additional Practice

Appendix — NumPy Cheatsheet & Pitfalls

## Environment check

Use the Python environment provided for the course and select its Jupyter kernel. Run the next cell before starting. If an import fails, stop and ask for help before continuing.


## Introduction — Why NumPy

NumPy provides the array model used directly or indirectly by Pandas, SciPy, scikit-learn, PyTorch, and many other AI tools. This week focuses on NumPy; later weeks will build on the same ideas of shape, data type, batching, and vectorized computation.

To build ML models or clean data effectively:
- Think in **arrays** (not lists) and **shapes**.
- Use **slicing** (prepares you for `.iloc`).
- Prefer **broadcasting & vectorization** over loops.
- Control **axis** semantics for aggregation.

> The exercises progress from foundational operations to more independent applications.

> Let's get started with importing NumPy!


In [ ]:
import sys
import numpy as np
import matplotlib.pyplot as plt

print("Python:", sys.version.split()[0])
print("NumPy:", np.__version__)
print("Environment check: OK")

np.set_printoptions(precision=3, suppress=True)

## 1. Arrays & Memory Model

### 1.1. Python Lists vs NumPy Arrays

A NumPy array has a single `dtype` and is designed for efficient numerical operations. Many arrays use contiguous memory, although slices and other views may be non-contiguous. Python lists store references to Python objects and may contain mixed types. NumPy's regular memory representation and vectorized operations are key reasons for its performance.

In [ ]:
#lst =

#arr =

print(type(lst))
print(type(arr))

### 1.2. NumPy Array Attributes

NumPy arrays have several important attributes that provide information about their structure and the data they hold. Some key attributes are:

- `shape`: A tuple that indicates the size of the array along each dimension.
- `dtype`: The data type of the elements in the array.
- `ndim`: The number of dimensions (axes) of the array.
- `size`: The total number of elements in the array.

In [ ]:
# Create a 2D NumPy array from scratch

#arr =

print(f'Array:\n{arr}', end='\n\n')
print(f'Shape: {arr.shape}', end='\n\n')
print(f'Data type: {arr.dtype}', end='\n\n')
print(f'Number of dimensions: {arr.ndim}', end='\n\n')
print(f'Size: {arr.size}')

### 1.3. Creating NumPy arrays
Many exercises use NumPy functions to generate arrays and matrices. Some common functions are presented below:

`np.arange(start, stop, step)`: Creates an array with evenly spaced values within a given interval. It works similarly to Python's built-in `range()` function.

- `start`: The beginning of the interval (optional, default is 0).
- `stop`: The end of the interval (exclusive).
- `step`: The spacing between values (optional, default is 1).

**Examples**:

- `np.arange(10)`: Generates an array `[0 1 2 3 4 5 6 7 8 9]`

- `np.arange(2, 10, 2)`: Generates an array `[2 4 6 8]`

In [ ]:
np.arange(10)

**Try it too!**

In [ ]:
# create a numpy array with [1, 2, 3] and print it


In [ ]:
# create a numpy array with arange and print it


Besides `np.arange` here are other common ways to create NumPy arrays:

In [ ]:
# Create an array of zeros
zeros_arr = np.zeros((3, 4))
print("np.zeros((3, 4)):\n", zeros_arr)

# Create an array of ones
ones_arr = np.ones((2, 5))
print("\nnp.ones((2, 5)):\n", ones_arr)

# Create an array filled with a specific value
full_arr = np.full((4, 2), 7)
print("\nnp.full((4, 2), 7):\n", full_arr)

# Create an identity matrix
identity_arr = np.eye(5)
print("\nnp.eye(5):\n", identity_arr)

# Create an array with evenly spaced values over a specified interval
linspace_arr = np.linspace(0, 10, 5) # 5 values between 0 and 10 (inclusive)
print("\nnp.linspace(0, 10, 5):\n", linspace_arr)

### Exercise 1.1 — Create & Inspect
Create an array with shape `(4, 5)` of values `0..19`. Print its `shape`, `dtype`, and `ndim`.


In [ ]:
# your code here


### 1.4. Reshape

Reshaping allows you to change the dimensions of an array without changing the data it contains.

**This is the combination of `np.arange()` and `reshape()` to create multi-dimensional arrays.**
```python
np.arange(12).reshape(3, 4)

>>> array([[ 0,  1,  2,  3],
           [ 4,  5,  6,  7],
           [ 8,  9, 10, 11]])
```

**The number of elements in the array must match the product of the dimensions specified in `reshape()`.**

**Try it too!**

In [ ]:
# Create a NumPy array with arange, reshape it to (5, 4), and print it


In [ ]:
# Create a NumPy array with arange, reshape it to (5, 4, 2), and print it


### Exercise 1.2 — Reshape
Create a 1D array using `np.arange` with 12 elements. Reshape it into a 2D array with shape (3, 4) and then reshape the 2D array into a 3D array with shape (2, 3, 2). Print the shape of each array after reshaping.

In [ ]:
# your code here


In [ ]:
# your code here


### 1.5. Typed arrays

We can specify the data type of the elements in a NumPy array using the `dtype` parameter when creating the array. This is useful for optimizing memory usage and ensuring that the data is stored in the desired format.

**Examples:**

```python
np.array([1, 2, 3], dtype=np.float32)
>>> array([1., 2., 3.], dtype=float32)
```

```python
np.arange(10, dtype=np.int16)
>>> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)
```
### Exercise 1.3 — Typed arrays

Create a float32 array of shape `(3, 3)` with values `0..8` and print its `dtype`


In [ ]:
# your code here


## 2. Mastering Slicing & Indexing (Core for `.iloc` later)

### 2.1. 1D Indexing & Slicing
Accessing elements or subsets of a 1D array is done using indexing and slicing.

- **Indexing:** Use square brackets `[]` with an integer to access a single element.
- **Slicing:** Use the colon `:` to specify a range of elements. The syntax is `[start:stop:step]`.
    - `start`: The starting index (inclusive). If omitted, it defaults to the beginning of the array.
    - `stop`: The ending index (exclusive). If omitted, it defaults to the end of the array.
    - `step`: The step size between elements. If omitted, it defaults to 1.

Negative indices count from the end of the array. For example, `[-1]` is the last element, `[-2]` is the second to last, and so on.

In [ ]:
# your code here


### Exercise 2.1 — 1D slicing drills
From `x = np.arange(20)`, produce:  
a) `x` without the first and last 2 elements.  
b) Elements at odd positions (1,3,5,...) using slicing.  
c) Reverse `x`.


In [ ]:
# your code here


### 2.2. 2D Slicing — Rows, Columns, Blocks
For 2D arrays (matrices), you use a comma to separate the slicing for each dimension (axis). The syntax is `[row_slice, column_slice]`.

- To select a specific row, use the row index and a colon for the column slice (e.g., `M[2, :]` selects the third row).
- To select a specific column, use a colon for the row slice and the column index (e.g., `M[:, 3]` selects the fourth column).
- To select a block or submatrix, specify the slice for both rows and columns (e.g., `M[1:4, 1:4]` selects rows 1 to 3 and columns 1 to 3).
- Use `:` by itself to select all elements along that axis.

In [ ]:
M = np.arange(25).reshape(5,5)
row2 = M[2,:]
col3 = M[:,3]
block = M[1:4, 1:4]
row2, col3, block

### Exercise 2.2 — Extract submatrices
From `G = np.arange(49).reshape(7,7)`, extract:  
a) Center 3×3 block.  
b) Top‑left 2×4 block.  
c) Last 3 rows and last 2 columns (as a block).


In [ ]:
G = np.arange(49).reshape(7,7)
G

In [ ]:
# your code here


### Exercise 2.3 Steps, Negative Indices
Use steps to subsample

From `G = np.arange(36).reshape(6,6)`

We want to obtain:

````
array([[ 5,  4,  3,  2,  1,  0],
       [17, 16, 15, 14, 13, 12],
       [29, 28, 27, 26, 25, 24]])
````


In [ ]:
G = np.arange(36).reshape(6,6)
G

In [ ]:
# your code here


## 3. Reshaping, Stacking, Concatenation

Reshape, stacking and concatenation are powerful tools in NumPy that allow you to manipulate the structure of your arrays in various ways. Here are some common operations:

- `arr.reshape(new_shape)`: Changes the shape of an array without changing its data. The new shape must be compatible with the original shape.
- `np.vstack((arr1, arr2))`: Stacks arrays vertically (row-wise).
- `np.hstack((arr1, arr2))`: Stacks arrays horizontally (column-wise).
- `np.concatenate((arr1, arr2), axis=0)`: Joins arrays along an existing axis. Use `axis=1` to join columns.

For example:

```python
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.vstack((A, B))  # Vertical stack
D = np.hstack((A, B))  # Horizontal stack
E = np.concatenate((A, B), axis=0)  # Concatenate along rows
F = np.concatenate((A, B), axis=1)  # Concatenate along columns

print("Vertical Stack:\n", C)
print("Horizontal Stack:\n", D)
print("Concatenate along rows:\n", E)
print("Concatenate along columns:\n", F)
```


In [ ]:
# check the result if each operation


### Exercise 3.1 — Reshape & Stack
Create two 2D arrays `A` and `B` of shape `(2, 3)` with values `0..5` and `6..11` respectively.

Stack them **vertically** and **horizontally**, and then **concatenate** them along both axes. Print the resulting arrays.

In [ ]:
# your code here


## 4. Broadcasting

Broadcasting is a powerful mechanism that allows NumPy to perform operations on arrays of different shapes in a way that makes sense mathematically. It works by "stretching" the smaller array across the larger one so that they have compatible shapes for element-wise operations.

For example in a given numpy array `A` of shape `(3, 4)`, if you want to add a 1D array `b` of shape `(4,)` to each row of `A`, NumPy will automatically "broadcast" `b` across the rows of `A`. This means that `b` is treated as if it were repeated for each row, allowing the addition to be performed element-wise.

**Note that `b` must have a shape that is compatible with `A` for broadcasting to work.**

```python
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

b = np.array([10, 20, 30, 40])

C = A + b

print(C)

>>> array([[11, 22, 33, 44],
           [15, 26, 37, 48],
           [19, 30, 41, 52]])
```

### Exercise 4.1 — Broadcasting drills

Given a 2D array `M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`
- a) Add `[10, 20, 30]` to each row of `M`.
- b) Subtract `[1, 2, 3]` from each column of `M`.
- c) Multiply each element of `M` by `2`.

In [ ]:
# your code here


## 5. Vectorization

Vectorization refers to the process of performing operations on entire arrays or large chunks of data at once, rather than using explicit loops to iterate over individual elements. This approach leverages optimized, low-level implementations in libraries like NumPy, which can lead to significant performance improvements.

**Examples**:

Given two 1D arrays:
```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
```
- Element-wise sum
    ```python
    sum_ab = a + b  # array([5, 7, 9])
    ```
- Element-wise product
    ```python
    prod_ab = a * b  # array([ 4, 10, 18])
    ```
- Dot product
    ```python
        dot_ab = np.dot(a, b) # 32 -> this is equivalent to np.sum(a * b)
    ```
- Euclidean distance
    ```python
    euclidean_dist = np.linalg.norm(a - b)  # 5.196152422 -> this is equivalent to np.sqrt(np.sum((a - b) ** 2))
    ```

### Exercise 5.1 — Vectorized operations

Given two 1D arrays `a = np.array([1, 2, 3])` and `b = np.array([4, 5, 6])`, compute their:

- a) Element-wise sum.
- b) Element-wise product.
- c) Dot product.
- d) Euclidean distance between `a` and `b`.

In [ ]:
# your code here


### Exercise 5.2 — From a loop to a vectorized operation

The loop below squares every value and adds 1. Produce the same result with a single vectorized NumPy expression. Use `np.array_equal` to verify that both results are identical. Then compare the execution times.

> Timing results depend on the computer and should be interpreted comparatively, not as fixed values.

In [ ]:
values = np.arange(100_000)

loop_result = []
for value in values:
    loop_result.append(value ** 2 + 1)
loop_result = np.array(loop_result)

# Replace the placeholder with one vectorized NumPy expression
vectorized_result = ...

# Verify that the two approaches return the same values
# np.array_equal(loop_result, vectorized_result)

# After obtaining a correct result, compare both approaches:
# %timeit [value ** 2 + 1 for value in values]
# %timeit values ** 2 + 1


## 6. Axis Operations & Aggregations

Many NumPy functions allow you to specify an `axis` parameter to control the direction of the operation. This is particularly useful for aggregations like sum, mean, max, etc.

The best way to understand axis operations is to think of them in terms of rows and columns in a 2D array (matrix).

### Exercise 6.1 — Axis sums
Given a 2D array `M = np.arange(1, 13).reshape(3, 4)`, compute:  
a) Sum of each column.  
b) Sum of each row.

Tips:
- Use `np.sum()` function with the `axis` parameter to compute these sums along the desired axis.

In [ ]:
# your code here


### Exercise 6.2 — Axis means
Given a 2D array `M = np.arange(1, 13).reshape(3, 4)`, compute:  
a) Mean of each column.  
b) Mean of each row.

Tips:
- Use `np.sum()` and `np.mean()` functions with the `axis` parameter to compute these statistics along the desired axis.

In [ ]:
# your code here


### Exercise 6.3 — Axis max/min
Given a 2D array `M = np.arange(1, 13).reshape(3, 4)`, compute:  
a) Max of each column.  
b) Min of each row.

Tips:
- Use `np.max()` and `np.min()` functions with the `axis` parameter to compute these statistics along the desired axis.

In [ ]:
# your code here


### Exercise 6.4 — Axis std/var
Given a 2D array `M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`, compute:  
a) Standard deviation of each column.
b) Variance of each row.

Tips:
- Use `np.std()` and `np.var()` functions with the `axis` parameter to compute these statistics along the desired axis.

In [ ]:
# your code here


### Exercise 6.5 — Axis argmax/argmin

`argmax` and `argmin` return the indices of the maximum and minimum values along a specified axis.

Given a 2D array `M = np.array([[1, 3, 2], [4, 0, 6], [7, 5, 8]])`, compute:  
a) Index of max in each column.  
b) Index of min in each row.

Tips:
- Use `np.argmax()` and `np.argmin()` functions with the `axis` parameter to compute these indices along the desired axis.

In [ ]:
# your code here


### Exercise 6.6 — Axis argwhere

`argwhere` returns the indices of elements that satisfy a given condition.

Given a 2D array `M = np.array([[1, 3, 2], [4, 0, 6], [7, 5, 8]])`, find the indices of all elements greater than 4.
Tips:
- Use `np.argwhere()` function to find the indices of elements that satisfy a given condition.

In [ ]:
# your code here


### Exercise 6.7 Sorting

Sorting arrays is a common operation in data analysis. NumPy provides functions to sort arrays along specified axes.

Sort the matrix along rows, columns and sort the whole matrix.
Given a 2D array `M = np.array([[1, 3, 2], [4, 0, 6], [7, 5, 8]])`

Tips:
- Use `np.sort()` function with the `axis` parameter to sort the array along the desired axis.

**Note: We can sort the whole matrix we by using `np.sort(M, axis=None)` but this will not preserve the original shape of the array, you might need to reshape it back to the original dimensions.**

In [ ]:
# your code here


## 7. Transposing

Transposing and rotating arrays are common operations in data manipulation.

Transposing an array involves swapping its rows and columns. In NumPy, this can be done using the `.T` attribute or the `np.transpose()` function.

**For example**:

```python
H = np.arange(12).reshape(3,4)
print(H)
H_transposed = H.T
print(H_transposed)

>>> array([[ 0,  1,  2,  3],
           [ 4,  5,  6,  7],
           [ 8,  9, 10, 11]])

>>> array([[ 0,  4,  8],
           [ 1,  5,  9],
           [ 2,  6, 10],
           [ 3,  7, 11]])
```


### Exercise 7.1 — Transpose & Rotations  

For `H = np.arange(9).reshape(3,3)`:

- a) Compute `H.T`. Print it before and after transposing
- b) Multiply `H x H.T`. Anything interesting here?

In [ ]:
# your code here


## 8. Challenging Exercises

### Cosine Similarity

Cosine similarity is a measure of similarity between two non-zero vectors of an inner product space.

It is defined as the cosine of the angle between the two vectors, which can be computed using the dot product and the magnitudes (norms) of the vectors.

$$
\text{cosine\_similarity}(A, B) = \frac{A \cdot B}{\|A\| \|B\|}
$$

Where:

$$
\|X\| = \sqrt{x_1^2 + x_2^2 + ... + x_n^2}
$$

### Exercise 8.1. Implement a function to compute the cosine similarity between two vectors.

```python
def cosine_similarity(A, B):
    # Your code here
    return similarity
```
**Example:**

```python
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
similarity = cosine_similarity(A, B)
print(similarity)  # Output: 0.9746318461970762
```

In [ ]:
# your code here


### Exercise 8.2. Extend the `Exercise 8.1` function to compute the cosine similarity matrix for a set of vectors, where each entry `(i, j)` represents the cosine similarity between vectors `i` and `j`.

```python
def cosine_similarity_matrix(vectors):
    # Your code here
    return similarity_matrix
```
**Example:**

```python
    A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    similarity_matrix = cosine_similarity_matrix(A)
    print(similarity_matrix)
    # Output:
    # [[1.         0.97463185 0.95941195]
    #  [0.97463185 1.         0.99819089]
    #  [0.95941195 0.99819089 1.        ]]
```

In [ ]:
# your code here


### Z-score normalization

Z-score normalization (or standardization) is a technique used to standardize the features of a dataset. It transforms the data such that the mean of each feature becomes 0 and the standard deviation becomes 1.

This is particularly useful in algorithms that are sensitive to the scale of the input data.

**Algorithm:**
1. Compute the mean of each column in the dataset.
2. Compute the standard deviation of each column in the dataset.
3. Subtract the mean from each value and divide by the standard deviation for each column.

> Before dividing, consider what should happen if a column has a standard deviation of zero.

### Exercise 8.3. Implement a function `zscore(X)` returning column‑wise standardized data (mean≈0, std≈1).

```python
def zscore(X):
    # Your code here
    return standardized_X
```

**Example:**

```python
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
standardized_X = zscore(X)
print(standardized_X)
# Output:
# [[-1.22474487 -1.22474487 -1.22474487]
#  [ 0.          0.          0.        ]
#  [ 1.22474487  1.22474487  1.22474487]]
```

In [ ]:
# your code here


## 9. Additional Practice

**R1 — Creation**
a) Create an `int32` array with values `0..35` (inclusive) and reshape to `(6, 3, 2)`.  
b) Print `shape`, `ndim`, `dtype`, `size`.  


In [ ]:
# your code here


**R2 — Dtypes & Itemsize**  
Create a `(4, 4)` array of `float32` numbers and print the `dtype` and `itemsize`.  


In [ ]:
# your code here


**R3 — Row/Column Sums via Slicing**  
Given `A = np.arange(36).reshape(6,6)`, compute:  
a) The sum of **rows 1..3** (inclusive).  
b) The sum of **columns 2..5** (inclusive).  
> *Tip:* Use `A[1:4, :]` and `A[:, 2:6]` then `.sum(axis=...)`.


In [ ]:
# your code here


**R4 — Stats on Specific Columns**  
Create `B = np.random.default_rng(0).normal(size=(200,4))`. Compute the **mean**, **median**, and **standard deviation** of the third column, whose zero-based index is `2`.  


In [ ]:
# your code here


**R5 — Create a NumPy array with 15 elements, reshape it to `(3, 5)`, and obtain the sum of the last column.**

**Tip**: use `np.sum()`

**Example**:
```python
arr = np.array([1, 2, 3])
np.sum(arr)

>>> 6
```

In [ ]:
# your code here


**R6 — Create a NumPy array with 15 elements, reshape it to `(5, 3)`, and obtain the mean of the middle column.**

**Tip**: use `np.mean()`

**Example**:
```python
arr = np.array([1, 2, 3])
np.mean(arr)

>>> 2
```

In [ ]:
# your code here


**R7 — From `G = np.arange(64).reshape(8,8)`, extract**:  
a) Top-left `3×3` block.  
b) Center `4×4` block.  
c) Bottom-right `2×5` block.  


In [ ]:
# your code here


**R8 — Symmetrize a matrix**

For `H = np.arange(16).reshape(4, 4)`, create a symmetric matrix using `(H + H.T) / 2`. Verify the result with `np.allclose(result, result.T)`.


In [ ]:
# your code here


**R9 — Column Mean-Centering**  
Create an array with shape `(300, 3)` using `np.random.default_rng(0).normal(size=(300, 3))`. Mean-center each column using broadcasting so that every column has a mean close to zero.

> Tip: Compute the mean of each column with `X.mean(axis=0)`, subtract it from `X`, and verify the result by calculating the new column means. Mean-centering is not the same as z-score standardization because it does not divide by the standard deviation.

In [ ]:
# your code here


**R10 — Given `P (120×2)` and `Q (120×1)`, stack side-by-side to shape `(120,3)`**.

In [ ]:
# your code here


**R11 — For `S = np.arange(100).reshape(10,10)`, compute**:
- a) Mean of **rows 2..6**.  
- b) Median of **columns 4..9**.  
- c) Std of the **center 4×4** block.

In [ ]:
# your code here


## Advanced NumPy Exercises for AI

The following exercises combine only the NumPy operations introduced in this notebook. These patterns will later be useful for organising datasets, working with batches, transforming features, and comparing observations. No new machine learning concepts are required here.

**R12 — Reshape and reorganise batches**

Arrays with three dimensions are often used to organise several observations into groups. Here we will focus only on reshaping and axis order.

a) Reshape `data` from `(10, 12)` to `(10, 3, 4)`.  
b) Extract the second group of four values from the last five observations. The result must have shape `(5, 4)`.  
c) Swap the last two axes to obtain an array with shape `(10, 4, 3)`.  
d) Restore the original `(10, 12)` arrangement and verify it with `np.array_equal`.

In [ ]:
# What we have: 10 observations, each containing 12 sequential values.
data = np.arange(120).reshape(10, 12)

# Expected shapes:
# batched.shape    -> (10, 3, 4)
# selected.shape   -> (5, 4)
# transposed.shape -> (10, 4, 3)
# restored.shape   -> (10, 12)
#
# Expected selected values:
# [[ 64,  65,  66,  67],
#  [ 76,  77,  78,  79],
#  [ 88,  89,  90,  91],
#  [100, 101, 102, 103],
#  [112, 113, 114, 115]]
# np.array_equal(restored, data) should return True.

# your code here


**R13 — Standardise columns safely**

Applying the same transformation independently to each column is a common use of broadcasting. One column below is constant and requires special care.

a) Compute the mean and standard deviation of every column.  
b) Create `safe_std` as a copy of the standard deviations and replace every zero with `1`.  
c) Standardise every column using broadcasting.  
d) Print the resulting column means and standard deviations. Explain the result for the constant column.

In [ ]:
# What we have: 5 observations and 4 columns.
# The third column is constant, so its standard deviation is zero.
X = np.array([[1., 10., 5., 2.],
              [2., 20., 5., 4.],
              [3., 30., 5., 6.],
              [4., 40., 5., 8.],
              [5., 50., 5., 10.]])

# Expected intermediate results:
# column_means -> [ 3., 30.,  5.,  6.]
# column_stds  -> approximately [1.414, 14.142, 0., 2.828]
#
# Expected verification after safe standardisation:
# standardised.mean(axis=0) -> [0., 0., 0., 0.]
# standardised.std(axis=0)  -> [1., 1., 0., 1.]
# The constant column remains zero after centering.

# your code here


**R14 — Combine Boolean masks and axis operations**

Boolean masks make it possible to inspect and correct selected values without iterating over the entire array.

a) Count the negative values in each column of `X`.  
b) Use `np.argwhere` to obtain their row and column positions.  
c) Create a copy called `X_clean` and replace its negative values with zero.  
d) In the same copy, replace values greater than 10 with 10.  
e) Verify that every value in `X_clean` is between 0 and 10.

In [ ]:
# What we have: a small matrix containing negative values and values above 10.
X = np.array([[3., -1., 7., 12.],
              [-2., 5., 11., 4.],
              [8., 2., -6., 15.],
              [0., 9., 3., -4.]])

# Expected results:
# negative_counts -> [1, 1, 1, 1]
# negative_positions -> [[0, 1], [1, 0], [2, 2], [3, 3]]
# X_clean ->
# [[ 3., 0.,  7., 10.],
#  [ 0., 5., 10.,  4.],
#  [ 8., 2.,  0., 10.],
#  [ 0., 9.,  3.,  0.]]
# The final range check should return True.

# your code here


**R15 — Pairwise Euclidean distances without loops**

Distances are useful whenever rows of data need to be compared. This exercise extends the Euclidean distance already used in Section 5.

Given `A` with shape `(4, 3)` and `B` with shape `(6, 3)`, compute a matrix `D` with shape `(4, 6)`, where `D[i, j]` is the Euclidean distance between rows `A[i]` and `B[j]`.

a) Use `A[:, None, :] - B[None, :, :]` to construct all pairwise differences.  
b) Square the differences, sum along the correct axis, and take the square root.  
c) Return the index of the closest row in `B` for every row in `A`.  
d) Compute the distance matrix between `A` and itself and verify that its diagonal is zero.

In [ ]:
# What we have: 4 rows in A and 6 rows in B; every row has 3 values.
A = np.array([[0., 0., 0.], [1., 2., 1.], [3., 1., 2.], [2., 2., 4.]])
B = np.array([[0., 1., 0.], [1., 1., 1.], [2., 2., 2.],
              [4., 0., 1.], [3., 3., 3.], [1., 0., 4.]])

# Expected results:
# differences.shape -> (4, 6, 3)
# D.shape           -> (4, 6)
# D[0] rounded to 3 decimals -> [1.000, 1.732, 3.464, 4.123, 5.196, 4.123]
# closest_indices -> [0, 1, 2, 4]
# The diagonal check for distances between A and itself should return True.

# your code here


**R16 — Combine feature blocks and rank results**

This final exercise combines the main operations from the notebook. Similar sequences of array transformations will later appear inside data and modelling workflows.

a) Join `block_a` and `block_b` horizontally to create `X` with shape `(6, 5)`.  
b) Mean-center every column using broadcasting.  
c) Compute one value per row using the dot product between the centered matrix and `weights`.  
d) Obtain the row indices that order these values from highest to lowest.  
e) Create a final matrix with two columns: the ordered original row indices and their corresponding values.

In [ ]:
# What we have: two blocks describing the same 6 rows.
# block_a has 2 columns and block_b has 3 columns.
block_a = np.array([[2., 5.], [4., 3.], [6., 8.],
                    [1., 7.], [5., 2.], [3., 6.]])
block_b = np.array([[1., 0., 2.], [2., 1., 0.], [0., 3., 1.],
                    [3., 2., 4.], [1., 4., 2.], [2., 0., 3.]])
weights = np.array([0.5, -0.25, 1.0, 0.75, -0.5])

# Expected results:
# X.shape -> (6, 5)
# values rounded to 3 decimals -> [-2.458, 1.792, 0.542, -0.958, 2.792, -1.708]
# order -> [4, 1, 2, 3, 5, 0]
# final_matrix ->
# [[ 4.   ,  2.792],
#  [ 1.   ,  1.792],
#  [ 2.   ,  0.542],
#  [ 3.   , -0.958],
#  [ 5.   , -1.708],
#  [ 0.   , -2.458]]

# your code here


## Appendix — NumPy Cheatsheet & Pitfalls
**Cheatsheet**
- Creation: `np.array`, `np.arange`, `np.linspace`, `np.zeros`, `np.ones`, `np.eye`
- Types: `arr.dtype`, cast with `arr.astype(...)`, `arr.itemsize`
- Shapes: `arr.shape`, `arr.ndim`, `arr.size`, `arr.reshape`, `arr.ravel`
- Indexing: `arr[i,j]`, slices (`start:stop:step`), fancy indexing
- Stacking: `np.vstack`, `np.hstack`, `np.concatenate([...], axis=...)`
- Aggregations: `mean`, `std`, `sum`, `max`, `argmax` with `axis=`
- Linear algebra: `np.dot`, `@`, `np.linalg.norm`

**Pitfalls**
- Basic slices usually create **views**, so mutations may affect the original array. Fancy indexing creates **copies**.
- Beware of shape mismatches in broadcasting; add axes with `None/np.newaxis`.
- **Keep track of shapes between steps; print shapes often**
